
package hightunes;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HighTunesService", targetNamespace = "http://HighTunes/", wsdlLocation = "http://localhost:1664/truc?WSDL")
public class HighTunesService
    extends Service
{

    private final static URL HIGHTUNESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(hightunes.HighTunesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = hightunes.HighTunesService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:1664/truc?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:1664/truc?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HIGHTUNESSERVICE_WSDL_LOCATION = url;
    }

    public HighTunesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HighTunesService() {
        super(HIGHTUNESSERVICE_WSDL_LOCATION, new QName("http://HighTunes/", "HighTunesService"));
    }

    /**
     * 
     * @return
     *     returns HighTunes
     */
    @WebEndpoint(name = "HighTunesPort")
    public HighTunes getHighTunesPort() {
        return super.getPort(new QName("http://HighTunes/", "HighTunesPort"), HighTunes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HighTunes
     */
    @WebEndpoint(name = "HighTunesPort")
    public HighTunes getHighTunesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://HighTunes/", "HighTunesPort"), HighTunes.class, features);
    }

}
