
package hightunes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HighTunes", targetNamespace = "http://HighTunes/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HighTunes {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toString", targetNamespace = "http://HighTunes/", className = "hightunes.ToString")
    @ResponseWrapper(localName = "toStringResponse", targetNamespace = "http://HighTunes/", className = "hightunes.ToStringResponse")
    public String toString();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connexion", targetNamespace = "http://HighTunes/", className = "hightunes.Connexion")
    @ResponseWrapper(localName = "connexionResponse", targetNamespace = "http://HighTunes/", className = "hightunes.ConnexionResponse")
    public int connexion();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deconnexion", targetNamespace = "http://HighTunes/", className = "hightunes.Deconnexion")
    @ResponseWrapper(localName = "deconnexionResponse", targetNamespace = "http://HighTunes/", className = "hightunes.DeconnexionResponse")
    public void deconnexion(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "viderPanier", targetNamespace = "http://HighTunes/", className = "hightunes.ViderPanier")
    @ResponseWrapper(localName = "viderPanierResponse", targetNamespace = "http://HighTunes/", className = "hightunes.ViderPanierResponse")
    public void viderPanier(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns hightunes.Article
     * @throws ArticleInexistant_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArticle", targetNamespace = "http://HighTunes/", className = "hightunes.GetArticle")
    @ResponseWrapper(localName = "getArticleResponse", targetNamespace = "http://HighTunes/", className = "hightunes.GetArticleResponse")
    public Article getArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ArticleInexistant_Exception
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNbTotalArticle", targetNamespace = "http://HighTunes/", className = "hightunes.GetNbTotalArticle")
    @ResponseWrapper(localName = "getNbTotalArticleResponse", targetNamespace = "http://HighTunes/", className = "hightunes.GetNbTotalArticleResponse")
    public int getNbTotalArticle();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws ArticleInexistant_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addToPanier", targetNamespace = "http://HighTunes/", className = "hightunes.AddToPanier")
    @ResponseWrapper(localName = "addToPanierResponse", targetNamespace = "http://HighTunes/", className = "hightunes.AddToPanierResponse")
    public void addToPanier(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Article arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws ArticleInexistant_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculCoutPanier", targetNamespace = "http://HighTunes/", className = "hightunes.CalculCoutPanier")
    @ResponseWrapper(localName = "calculCoutPanierResponse", targetNamespace = "http://HighTunes/", className = "hightunes.CalculCoutPanierResponse")
    public float calculCoutPanier(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ErreurPanier_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commander", targetNamespace = "http://HighTunes/", className = "hightunes.Commander")
    @ResponseWrapper(localName = "commanderResponse", targetNamespace = "http://HighTunes/", className = "hightunes.CommanderResponse")
    public String commander(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ErreurPanier_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws ErreurPanier_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifierQuantite", targetNamespace = "http://HighTunes/", className = "hightunes.ModifierQuantite")
    @ResponseWrapper(localName = "modifierQuantiteResponse", targetNamespace = "http://HighTunes/", className = "hightunes.ModifierQuantiteResponse")
    public void modifierQuantite(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Article arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws ErreurPanier_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "suppressionArticle", targetNamespace = "http://HighTunes/", className = "hightunes.SuppressionArticle")
    @ResponseWrapper(localName = "suppressionArticleResponse", targetNamespace = "http://HighTunes/", className = "hightunes.SuppressionArticleResponse")
    public void suppressionArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Article arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "catalogueToString", targetNamespace = "http://HighTunes/", className = "hightunes.CatalogueToString")
    @ResponseWrapper(localName = "catalogueToStringResponse", targetNamespace = "http://HighTunes/", className = "hightunes.CatalogueToStringResponse")
    public String catalogueToString();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "panierToString", targetNamespace = "http://HighTunes/", className = "hightunes.PanierToString")
    @ResponseWrapper(localName = "panierToStringResponse", targetNamespace = "http://HighTunes/", className = "hightunes.PanierToStringResponse")
    public String panierToString(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns hightunes.Catalogue
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCat", targetNamespace = "http://HighTunes/", className = "hightunes.GetCat")
    @ResponseWrapper(localName = "getCatResponse", targetNamespace = "http://HighTunes/", className = "hightunes.GetCatResponse")
    public Catalogue getCat();

    /**
     * 
     * @return
     *     returns hightunes.HashMap
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListePaniers", targetNamespace = "http://HighTunes/", className = "hightunes.GetListePaniers")
    @ResponseWrapper(localName = "getListePaniersResponse", targetNamespace = "http://HighTunes/", className = "hightunes.GetListePaniersResponse")
    public HashMap getListePaniers();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setCat", targetNamespace = "http://HighTunes/", className = "hightunes.SetCat")
    @ResponseWrapper(localName = "setCatResponse", targetNamespace = "http://HighTunes/", className = "hightunes.SetCatResponse")
    public void setCat(
        @WebParam(name = "arg0", targetNamespace = "")
        Catalogue arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setListePaniers", targetNamespace = "http://HighTunes/", className = "hightunes.SetListePaniers")
    @ResponseWrapper(localName = "setListePaniersResponse", targetNamespace = "http://HighTunes/", className = "hightunes.SetListePaniersResponse")
    public void setListePaniers(
        @WebParam(name = "arg0", targetNamespace = "")
        HashMap arg0);

}
